![](images/image13.png)

OS Information

|     |     |
| --- | --- |
| Customer | Baker Street Corporation |
| Hostname | Baker\_Street\_Linux\_Server |
| OS Version | Ubuntu 22.04.5 LTS (Jammy Jellyfish) |
| Memory information | Total 15Gi, used 1.4Gi, free 8.4Gi, shared 198Mi, buff/cache 5.6Gi, available 13Gi |
| Uptime information | 00:12:06 up 26 min,  0 users,  load average: 1.22, 1.24, 1.03 |

Checklist

|     |     |     |
| --- | --- | --- |
| Completed | Activity | Script(s) used / Tasks completed / Screenshots |
|     |     |     |
|     | OS backup | *   HostName (command =hostname)<br>*   OS version (command =cat /etc/os-release)<br>*   Memory information  (command= free -h)<br>*   Uptime information (command =uptime)<br><br>![](images/image1.png)<br><br>sudo tar -cvpzf /baker\_street\_backup.tar.gz --exclude=/baker\_street\_backup.tar.gz --exclude=/proc --exclude=/tmp --exclude=/mnt --exclude=/sys --exclude=/dev --exclude=/run /<br><br>![](images/image37.png) |
|     | Auditing users and groups | 1.  Remove users, home directory and files<br><br>(command= sudo userdel -r mary, lestrade, irene, gregson)<br><br>![](images/image31.png)<br><br>2.  Lock users<br><br>(command = sudo passwd -S moriarty, mrs\_hudson)<br><br>![](images/image11.png)<br><br>3.  Unlock users<br><br>(command = sudo passwd -u sherlock, watson, mycroft, toby, adler)<br><br>*   Toby and adler = create password (sudo pass -S \_\_ ) then unlocked<br><br>![](images/image7.png)<br><br>5\. Create a research group<br><br>(command= sudo groupadd research) and add users to group (no members because none in marketing)<br><br>6\. Remove marketing group<br><br>(command= sudo groupdel marketing)<br><br>![](images/image14.png) |
|     | Updating and enforcing password policies | 1.  Update the password requirements for all users to have:<br><br>(command =sudo nano/etc/pam.d/common-password)<br><br>![](images/image32.png) |
|     | Updating and enforcing sudo permissions | 1.  Sudo visudo<br><br>*   Removed full sudo privileges beside Sherlocke<br>*   Watson and Mycroft should only have sudo privileges (script =watson  ALL=(ALL) NOPASSWD: /var/log/logcleanup.sh<br><br>mycroft  ALL=(ALL) NOPASSWD: /var/log/logcleanup.sh)<br><br>*   All employees who belong to the research group should have sudo privileges (script=<br><br>%research  ALL=(ALL) NOPASSWD: /tmp/scripts/research\_script.sh)<br><br>*   ![](images/image23.png) |
|     | Validating and updating permissions on files and directories | 1.  In every user’s home directory, there should be no files that have any world permissions to read, write, or execute.<br><br>*   Find any of them and update to remove the world permissions.<br><br>(command= find /home -type f -perm 777 -exec chmod 770 {} \\;)<br><br>2.  Revised shorter script (command =<br><br>find /home  -type f -iname '\*engineering\*' -exec chown :engineering {} +<br><br>find /home -type f  -iname '\*engineering\*' -exec chmod 770 {} +<br><br>*   Engineering scripts (command = find ./ -type f -iname “\*engineering\*”)<br><br>![](images/image45.png)<br><br>*   Change ownership (command=sudo chown 770 /home/mycroft/Engineering\_script.sh\_0.txt (etc)<br><br>![](images/image29.png)<br><br>*   Change permission (command =Sudo chmod 770 /home/toby/Engineering\_script.sh\_2.txt (![](images/image40.png)etc)<br>*   Check ( command =ls -l /home/\*/Engineering\_script.sh\*)  <br><br>![](images/image30.png)<br><br>3.  Nothing in research<br>4.  Revised shorter (command=<br><br>find /home type f  -iname '\*finance\*' -exec chown :finance {} +<br><br>find /home type f  -iname '\*finance\*' -exec chmod 770 {} +<br><br>![](images/image3.png)<br><br>![](images/image25.png)<br><br>![](images/image9.png)<br><br>5.  Some employees may leave files with hidden passwords. Find those files and remove them<br><br>(command= john /etc/shadow) crack the passwords<br><br>![](images/image4.png)<br><br>(command= find ./ -type f -iname "\*.txt\*") search all files in users’ home directories for the password<br><br>![](images/image15.png)<br><br>*   No hidden files with passwords |
|     | Optional: Updating password hashing configuration |     |
|     | Auditing and securing SSH | 1.  Configure SSH to not allow the ability to:<br><br>1.  SSH with empty passwords<br>2.  SSH with the root user<br>3.  SSH with any other ports besides 22<br><br>2.  Enable SSH protocol 2.<br>3.  Restart the SSH service to set your updates<br><br>![](images/image43.png)![](images/image36.png)![](images/image46.png)<br><br>![](images/image17.png) |
|     | Reviewing and updating system packages | 1.  Apt update<br><br>(command= sudo apt update)<br><br>![](images/image42.png)<br><br>2.  Update already installed packages to the latest version<br><br>(command= sudo apt upgrade -y)![](images/image20.png)<br><br>3.  Create file package\_list.txt which contains all installed packages<br><br>(command = apt list --installed)  List all installed packages.<br><br>![](images/image34.png)<br><br>4.  Redirect list and creates package\_list.txt<br><br>(command =apt list --installed > package\_list.txt)<br><br>![](images/image28.png)<br><br>5.  Check<br><br>(command =cat package\_list.txt)<br><br>![](images/image24.png)<br><br>6.  Identify if any of the following packages are on the list as having these could introduce a security issue<br><br>(command = grep -i "telnet" package\_list.txt and grep -i "rsh-client" package\_list.txt)<br><br>![](images/image27.png)<br><br>7.  If they are on the list, remove those packages.<br><br>(command=sudo apt remove --purge telnet rsh-client)<br><br>![](images/image2.png)<br><br>Security issues:<br><br>Telnet: Sends data (including login credentials) in plaintext, making it vulnerable to man-in-the-middle attacks and packet sniffing.<br><br>RSH (Remote Shell): Also transmits data in plaintext and does not authenticate the client-server connection properly, which makes it vulnerable to eavesdropping and attacks.<br><br>8.  Remove all unnecessary dependencies of those packages<br><br>(command=sudo apt autoremove  -y)<br><br>![](images/image35.png)<br><br>9.  Add packages ufw, lynis,tripwire<br><br>(command =sudo apt install ufw lynis tripwire -y)<br><br>![](images/image44.png)<br><br>10.  Hardening features:<br><br>UFW: Enables or disables specific ports to limit access and simplifies firewall management with intuitive commands.<br><br>Lynis: Performs a security audit to detect potential threats. Provides security recommendations to harden the system. Also checks for common vulnerabilities, such as weak permissions or misconfigured services.<br><br>Tripwire: Monitors critical files for changes (e.g., system binaries, configuration files). Also<br><br>alerts administrators of any unauthorized changes, helping to detect attacks. And can aid in detecting malware and other intrusions. |
|     | Disabling unnecessary services | 1.  List out all services. Output this into a file called service\_list.txt.<br><br>(command= service --status-all > service\_list.txt)<br><br>![](images/image6.png)![](images/image10.png)<br><br>8\. Identify if any of the following services are running: Mysql and Samba<br><br>(command= service \_\_\_ status)<br><br>9\. If any of the above services are running,<br><br>Stop them<br><br>(command= service\_\_ stop)<br><br>![](images/image26.png)![](images/image41.png)<br><br>11\. Disable them (cannot because of systemctl)<br><br>12\. Remove them<br><br>(command= apt remove \_\_\_\_)![](images/image19.png)<br><br>![](images/image8.png) |
|     | Enabling and configuring logging | 1.  Use nano to edit the following settings in the file. Be sure to uncomment the lines<br><br>1.  Set “storage=persistent”<br>2.  Set “systemMaxUse=300M”<br><br>2\. Go into and edit file<br><br>(command= sudo nano /etc/systemd/journald.conf)<br><br>![](images/image39.png)<br><br>![](images/image33.png)<br><br>3\. To prevent logs from taking up too much space, you will need to configure log rotation.<br><br>(command=sudo nano /etc/logrotate.conf)<br><br>![](images/image16.png)<br><br>4\. Edit the file: /etc/logrotate.conf with the following settings:<br><br>Change the log rotation from weekly to daily.<br><br>Rotate out the logs after 7 days.<br><br>![](images/image5.png) |
|     | Scripts created | Hardening\_script\_output.txt<br><br>![](images/image18.png)<br><br>![](images/image38.png)<br><br>Hardening\_script\_2\_output.txt<br><br>![](images/image21.png)<br><br>![](images/image22.png) |
|     | Scripts scheduled with cron | *   Using cron, schedule script 1 to run Once a month on the first of the month (command crontab -e)<br>*   Using cron, schedule script 2 to run Once a week every Monday (crontab -e)<br><br>![](images/image12.png) |
